version: '3'
services:
  app:
    build:
      context: .
      dockerfile: "Docker/php/Dockerfile"
#    ports:
#        - 127.0.0.1:9000:9000
    ports:
      - 8000:8000
    volumes:
      - ./www/:/var/www/
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=laravel
      - DB_USERNAME=root
      - DB_PASSWORD=secret
    depends_on:
      - db
    networks:
      - laravel
    command: php artisan serve --host 0.0.0.0

  db:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=laravel
      - MYSQL_ROOT_PASSWORD=secret
    volumes:
      - ./Docker/database:/var/lib/mysql
    networks:
      - laravel

  adminer:
    image: adminer:latest
    ports:
      - 8080:8080
    networks:
      - laravel
    depends_on:
      - db

  redisdb:
    image: redis
    restart: always
    volumes:
      - ./Docker/redis:/data
    networks:
      - laravel

#  horizon:
#    build:
#      context: .
#      dockerfile: "Docker/php/Dockerfile"
#    volumes:
#      - ./www/:/var/www/
#    working_dir: /var/www
#    command: php artisan horizon
#    #    user: "www-data:www-data"
#    depends_on:
#      - db
#      - redisdb
#    networks:
#      - laravel

networks:
  laravel: